apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lk7d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-lk7d@sha256:7e660d4ae7bdd39c506106bfb43b709e67fbc63677f0e8327ab5b5138cca3d78
        name: my-nodejs
        resources: {}
status: {}
